### ISSUE TITLE
PostgreSQL support

### ISSUE THREAD

**Issue by cisbrh** [phpenv/phpenv#53] opened 2014-07-11 21:38 UTC
I tried to use Codeship for our CI but they are telling me that for version above 5.3 phpenv does not have the PDO drivers for postgresql. Can someone confirm this and if so is there way to have it in the next release.
Thanks

**Comment by madumlao** [comment] 2018-10-05 05:33
Closing as a duplicate of #57 

phpenv has changed dramatically since the last release due to the project having basically died and just recently being revived in #85. phpenv supports postgresql (or pretty much any PHP feature).

Right now, phpenv relegates build functionality to [php-build](https://github.com/php-build/php-build), which runs the `./configure` `make` `make install` steps with the appropriate args and environment to install PHP into your local prefix.

Additional `./configure` options can be passed into phpenv via the environment variable `PHP_BUILD_CONFIGURE_OPTS`. For example, you may specify `--with-pgsql=DIR` `--with-pdo-pgsql=DIR` to direct the configure script on how to find the postgres / PDO library directories.

php-build man page can be found here:

https://github.com/php-build/php-build/blob/master/man/php-build.1.ronn

The latest phpenv + php-build combo can be installed using the installer script, [phpenv-installer](https://github.com/phpenv/phpenv-installer)

**Closed by madumlao** 2018-10-05 05:33 UTC
