### ISSUE TITLE
I cant install version on Ubuntu

### ISSUE THREAD

**Issue by lukashes** [phpenv/phpenv#49] opened 2014-04-16 10:49 UTC
I have Ubuntu 12.04, I tried on master branch:

> phpenv install php-5.3.10

log:

Building php-5.3.10

```
[Fetching]:  latest code from Github repo
[Branching]:  for a clean build environment
[Configuring]:  build options for selected release
```

BUILD ERROR
Switched to a new branch 'build' make: acconfig.h.in acinclude.m4 autom4te.cache build buildconf buildconf.bat CODING_STANDARDS config.guess config.sub configure configure.in CREDITS ext EXTENSIONS footer genfiles header INSTALL LICENSE ltmain.sh main makedist Makefile.frag Makefile.gcov Makefile.global makerpm netware NEWS pear php5.spec.in php.gif php.ini-development php.ini-production README.EXTENSIONS README.EXT_SKEL README.input_filter README.MAILINGLIST_RULES README.namespaces README.PARAMETER_PARSING_API README.PHP4-TO-PHP5-THIN-CHANGES README.REDIST.BINS README.RELEASE_PROCESS README.SELF-CONTAINED-EXTENSIONS README.STREAMS README.SUBMITTING_PATCH README.SVN-RULES README.TESTING README.TESTING2 README.UNIX-BUILD-SYSTEM README.WIN32-BUILD-SYSTEM README.Zeus run-tests.php sapi scripts server-tests-config.php server-tests.php snapshot stamp-h.in stub.c svnclean.bat tests TODO TODO-5.1 TODO-PHP5 TSRM UPGRADING UPGRADING.INTERNALS vcsclean win32 Zend [buildmk.stamp] Ошибка 1

The full Log is available here /tmp/phpenv-install-php-5.3.10.20140416144542.log

In log I see only:

$ cat /tmp/phpenv-install-php-5.3.10.20140416144542.log
Switched to a new branch 'build'
make: **\* [buildmk.stamp] Ошибка 1
Checking out files: 100% (6735/6735), done.
Switched to branch 'master'

Any ideas?

**Comment by cybernetlab** [comment] 2015-09-01 22:11
+1 on Linux Mint 17

**Comment by madumlao** [comment] 2018-10-05 06:04
Closing as a duplicate of #57.

phpenv has changed dramatically since the last release due to the project having basically died and just recently being revived in #85. Right now, all build functionality has been relegated to [php-build](https://github.com/php-build/php-build), which is activately updated with the latest PHP versions. All build issues should be raised there from now.

The latest phpenv + php-build combo can be installed using the [phpenv-installer](https://github.com/phpenv/phpenv-installer)

**Closed by madumlao** 2018-10-05 06:04 UTC
