### ISSUE TITLE
Installation broken

### ISSUE THREAD

**Issue by willfaught** [phpenv/phpenv#69] opened 2016-09-15 21:39 UTC
`phpenv install --releases` lists nothing, `phpenv install myversion` does nothing, master branch still works

**Comment by shogochiai** [comment] 2016-09-20 08:44
<img width="565" alt="ss 272" src="https://cloud.githubusercontent.com/assets/4891004/18663449/8276b8c4-7f59-11e6-94d0-964e3e005f26.png">

I got this error when executing `git submodule update`.

I think this relates to this.
https://github.com/phpenv/phpenv/blob/dev/libexec/phpenv-install#L140

**Comment by shogochiai** [comment] 2016-09-20 08:45
Oh yeah PR found
https://github.com/phpenv/phpenv/pull/48#issuecomment-40904139

**Comment by AppSynergy** [comment] 2016-09-27 14:39
Mongo seemed to be affected as well for me.

I checked out the latest master of both `pecl-http` and `mongo-php-driver`, which had the effect of adding:

````
init  the cloning of PHP source repository for the first time - please be patient this will only take a minute
````

to the output of `phpenv install --releases`. It still hangs..

**Comment by madumlao** [comment] 2018-10-05 03:54
Closing as a duplicate of #57 

phpenv should be working using the latest versions pulled by [phpenv-installer](https://github.com/phpenv/phpenv-installer)

**Closed by madumlao** 2018-10-05 03:54 UTC
