### ISSUE TITLE
Modularise configuration options

### ISSUE THREAD

**Issue by nickl-** [phpenv/phpenv#31] opened 2013-08-03 21:49 UTC
From @madumlao at [madumlao/phpenv#commitcomment-3555630](https://github.com/madumlao/phpenv/commit/e07f1d846b454ec32d7aef6544be48aba7e6ffcf#commitcomment-3555630)

For true reusability, what this needs is to break the CONFIGURE_OPTIONS into several commands, followed by a set of comments indicating which gentoo packages you need installed to properly support jpeg, png, etc etc, and what their default install paths end up being.

Here is what I figure

``` bash
# default configure options
CONFIGURE_OPTIONS="foo bar baz"

# enable image formats
CONFIGURE_OPTIONS="$CONFIGURE_OPTIONS --with-jpeg"

# enable fast process manager
CONFIGURE_OPTIONS="$CONFIGURE_OPTIONS --with-fpm"

# enable mysql
CONFIGURE_OPTIONS="$CONFIGURE_OPTIONS --with-mysqli --with-mysql-sock=/var/run/mysqld/mysqld.sock"

# enable library foo
# in ubuntu, library foo is installed into /usr/lib/foo-x.y
CONFIGURE_OPTIONS="$CONFIGURE_OPTIONS --enable-foo --with-foo-dir=/usr/lib/foo-x.y"
```

etc. That way you can use comments to indicate the default options for different distributions with minor performance hit. And changes will appear more meaningful to you on your git diffs.

**Comment by madumlao** [comment] 2018-10-05 07:16
The commiter has become the maintainer. The circle is complete ;)

Closing the issue as a duplicate of #57.

phpenv has changed dramatically since the last release due to the project having basically died and just recently being revived in #85. Specifically, phpenv now relegates build functionality to php-build. Build suggestions such as these may be raised there. Alternatively, a convenience plugin may be written that can make setting such configure options easy.

The latest phpenv + php-build combo now successfully builds without issues and can be installed using the installer script, [phpenv-installer](https://github.com/php-build/php-build).

**Closed by madumlao** 2018-10-05 07:16 UTC
