### ISSUE TITLE
Collision with rbenv

### ISSUE THREAD

**Issue by stevehill1981** [phpenv/phpenv#50] opened 2014-04-22 10:53 UTC
On my system, I have both rbenv/ruby-build and phpenv/php-build installed.

When I run phpenv, I get output referring to rbenv instead. I am unable to use phpenv/php-build to get a list of known releases, and also unable to install anything (as the version string is unrecognised as a valid ruby version).

I'm running Mac OS X Mavericks, and I installed all packages via Homebrew.

**Comment by nok** [comment] 2015-03-04 13:08
Hello, here the same with OS X Yosemite 10.10.2.

**Comment by joshuaspence** [comment] 2016-02-02 03:02
I have a similar issue. I am able to use `phpenv` but the help text refers to `rbenv` instead of `phpenv`. I also have to set the `RBENV_VERSION` environment variable instead of `PHPENV_VERSION`.

**Comment by stephenorr** [comment] 2016-12-19 10:01
This problem persists with the latest release, on MacOS Sierra.

Evidently I'm not the only person wanting to use both PHP and Ruby; for the time being I've gone back to just using Homebrew to install a specific fixed version of PHP, but I'd really find it useful to have `phpenv` working.

**Comment by madumlao** [comment] 2018-10-05 06:02
Closing as a duplicate of #57

phpenv has changed dramatically since the last release due to the project having basically died and just recently being revived in #85. Specifically, references to rbenv have been removed from phpenv.

I currently use the latest phpenv + php-build and rbenv + ruby-build and am encountering no issues.

The latest phpenv (with related plugins) can be installed using the installer script, [phpenv-installer](https://github.com/phpenv/phpenv-installer).

**Closed by madumlao** 2018-10-05 06:02 UTC
