### ISSUE TITLE
Solving installation problems - a process of elimination 

### ISSUE THREAD

**Issue by robblovell** [phpenv/phpenv#37] opened 2013-10-09 17:11 UTC
I installed phpenv on a clean 10.8.4 osx machine.  The commands all seem to work without error, but the php version doesn't change.  I noticed that there are no changes to the shim directory.  

<pre>
Robbs-MacBook-Air:~ robblovell$ phpenv version
5.5.4 (set by /Users/robblovell/.phpenv/version)
Robbs-MacBook-Air:~ robblovell$ ls .phpenv/shims/
Robbs-MacBook-Air:~ robblovell$ phpenv versions
phpenv v0.0.4-dev

  system
* 5.5.4 (set by /Users/robblovell/.phpenv/version)
Robbs-MacBook-Air:~ robblovell$ php --version
PHP 5.3.15 with Suhosin-Patch (cli) (built: Dec  9 2012 19:32:02)
Copyright (c) 1997-2012 The PHP Group
Zend Engine v2.3.0, Copyright (c) 1998-2012 Zend Technologies
    with Xdebug v2.2.3, Copyright (c) 2002-2013, by Derick Rethans
Robbs-MacBook-Air:~ robblovell$ ls -la shims
total 0
drwxr-xr-x   2 robblovell  staff   68  9 Oct 10:00 .
drwxr-xr-x  19 robblovell  staff  646  9 Oct 09:58 ..
Robbs-MacBook-Air:~ robblovell$ cat ~/.bash_profile
export PATH="~/.phpenv/shims:$HOME/.phpenv/bin:$PATH"
eval "$(phpenv init -)"
Robbs-MacBook-Air:~ robblovell$ cat .profile
PATH="$PATH:/usr/loc/bin"
Robbs-MacBook-Air:~ robblovell$
</pre>

I do have MAMP installed, not sure if that makes a difference, but it's not referenced:

<pre>
Robbs-MacBook-Air:~ robblovell$ which php
/usr/bin/php

</pre>

**Comment by ravinders-121** [comment] 2017-09-06 06:35
Editing file .phpenv/etc/config.source

to replace line

--with-readline \

with 

--with-libedit \

Fixed the error **"configure: error: invalid readline installation detected. Try --with-libedit instead."** for me.

**Comment by madumlao** [comment] 2018-10-05 05:02
Going to have to close this as a duplicate of #57 

phpenv build functionality is now relegated to [php-build](https://github.com/php-build/php-build), so build issues should now be raised there. It actually has a more active community than phpenv.

**Closed by madumlao** 2018-10-05 05:02 UTC

**Comment by ctsstc** [comment] 2020-10-28 10:12
Since I'm back here again trying to install `PHP 7.4.11` (7.4.10 last time) via asdf, it has similar issues.

```
brew install bison re2c openssl icu4c libiconv
# To override mac's built in old version if you're using zshrc
# brew should give you a heads up about this
echo 'export PATH="/usr/local/opt/bison/bin:$PATH"' >> ~/.zshrc

# To give some installers heads up about openssl
# brew should give you a heads up about this

# For compilers to find openssl@1.1 you may need to set:
export LDFLAGS="-L/usr/local/opt/openssl@1.1/lib $LDFLAGS"
export CPPFLAGS="-I/usr/local/opt/openssl@1.1/include $CPPFLAGS"

# For pkg-config to find openssl@1.1 you may need to set:
export PKG_CONFIG_PATH="/usr/local/opt/openssl@1.1/lib/pkgconfig"

# Add icu4c as well
export LDFLAGS="-L/usr/local/opt/icu4c/lib $LDFLAGS"
export CPPFLAGS="-I/usr/local/opt/icu4c/include $CPPFLAGS"
export PKG_CONFIG_PATH=/usr/local/opt/icu4c/lib/pkgconfig:$PKG_CONFIG_PATH    

# libiconv
export LDFLAGS="-L/usr/local/opt/libiconv/lib $LDFLAGS"    
export CPPFLAGS="-I/usr/local/opt/libiconv/include $CPPFLAGS"

```

**Comment by debo** [comment] 2020-10-28 10:19
@ctsstc you shouldn't really need anything of that as far I can tell. I did compile my 7.4 version without any issue. A different story goes for 7.2 and 7.3 since the recent changes in OSX as far as I understand.
