### ISSUE TITLE
Autoconf version related issues when compiling

### ISSUE THREAD

**Issue by mbfisher** [phpenv/phpenv#52] opened 2014-06-18 13:39 UTC
I've seen similar issues to this so I apologise if it's already been answered; I couldn't find a solution!

I'm having trouble installing 5.3.28 on OS X 10.8.4. I have autoconf 2.69 installed via homebrew for building extensions against 5.5.*, and I get the following:

``` bash
$> export LC_CTYPE=C LANG=C # To make sed play nicely
$> phpenv install php-5.3.28
phpenv v0.0.4-dev

/Users/mif08/.phpenv/php-src/php.ini-recommended gets used as php.ini
Building 5.3.28 with config options from: php-5.3.Darwin.source

                         [Fetching] |1| latest code from Github repo
                        [Branching] |2| for a clean build environment
                         [Patching] |3| Applying patches to the source if any are applicable.
                      [Configuring] |4| build options for selected release

BUILD ERROR: STATUS is 4
The script aborted unexpectedly when a command returned a non zero exit code.
Last 10 linens from the error log file may shed some light
-------------------------------------------------------------------------------------
Switched to branch 'master'
Switched to a new branch 'build'
make: *** [buildmk.stamp] Error 1

-------------------------------------------------------------------------------------

The full STDERR Log is available here /tmp/phpenv-install-php-5.3.28.20140618142337.log.err
The full STDOUT Log is available here /tmp/phpenv-install-php-5.3.28.20140618142337.log
The command to view the logfile with $PAGER has been copied to your clipboard.

$> cat /tmp/phpenv-install-php-5.3.28.20140618142337.log
Your branch is up-to-date with 'origin/master'.
~/.phpenv/php-src/ext ~/.phpenv/php-src ~
~/.phpenv/php-src ~
patching file /Users/mif08/.phpenv/php-src/Makefile.global
Hunk #1 succeeded at 18 (offset -2 lines).

./configure --with-apxs2=/usr/sbin/apxs --enable-zend-multibyte ...

/Users/mif08/.phpenv/phpenv.d/install/post-configure.bash
/Users/mif08/.phpenv/phpenv.d/install/pre-buildconf.bash
/Users/mif08/.phpenv/phpenv.d/install/pre-configure.bash
Forcing buildconf
buildconf: checking installation...
buildconf: autoconf not found.
           You need autoconf version 2.13 or newer installed
           to build PHP from SVN.
```
#34 suggested installing autoconf 2.13, which I compiled from source:

``` bash
$> /usr/local/bin/autoconf-2.13 --version
Autoconf version 2.13
```

And set the `PHP_AUTOCONF` environment variable as per PHP's `buildcheck.sh`:

``` bash
$> export PHP_AUTOCONF=/usr/local/bin/autoconf-2.13
```

And still get the same output as above. If I run `buildconf` by hand:

``` bash
$> cd ~/.phpenv/php-src
$> ./buildconf --force
Forcing buildconf
buildconf: checking installation...
buildconf: autoconf version 2.13 (ok)
...
```

Stumped. Any suggestions?

M

**Comment by madumlao** [comment] 2018-10-05 05:57
Closing as a duplicate of #57 

phpenv has changed dramatically since the last release due to the project having basically died and just recently being revived in #85.

Currently, phpenv relegates all build functionality to [php-build](https://github.com/php-build/php-build), which is more actively maintained with regards to build functionality than phpenv. Any build issues should be relegated there.

The latest phpenv + php-build can automatically be installed using [phpenv-installer](https://github.com/phpenv/phpenv-installer)

**Closed by madumlao** 2018-10-05 05:57 UTC
