### ISSUE TITLE
RBENV_VERSION environment variable is used

### ISSUE THREAD

**Issue by joshuaspence** [phpenv/phpenv#65] opened 2016-02-02 03:13 UTC
When I run `phpenv help` the output text seems to refer to `rbenv` rather than `phpenv`. Furthermore, the `PHPENV_VERSION` environment variable seems to do nothing whereas `RBENV_VERSION` seems to work.

```
> phpenv
rbenv 1.0.0-16-gd6ab394
Usage: rbenv <command> [<args>]

Some useful rbenv commands are:
   commands    List all available rbenv commands
   local       Set or show the local application-specific Ruby version
   global      Set or show the global Ruby version
   shell       Set or show the shell-specific Ruby version
   rehash      Rehash rbenv shims (run this after installing executables)
   version     Show the current Ruby version and its origin
   versions    List all Ruby versions available to rbenv
   which       Display the full path to an executable
   whence      List all Ruby versions that contain the given executable

See `rbenv help <command>' for information on a specific command.
For full documentation, see: https://github.com/rbenv/rbenv#readme

> phpenv version
rbenv: version `5.3.29' is not installed (set by RBENV_VERSION environment variable)
 (set by RBENV_VERSION environment variable)
```

**Comment by debo** [comment] 2016-03-21 14:23
@joshuaspence what version of phpenv are you using? Since this project seems to be abandoned I switched to [this fork](https://github.com/madumlao/phpenv) a while ago and never looked back since.

**Comment by madumlao** [comment] 2018-10-05 04:18
Closing as duplicate of #57 

All commands should be working in the current versions being pulled by [phpenv-installer](https://github.com/phpenv/phpenv-installer)

**Closed by madumlao** 2018-10-05 04:18 UTC
