### ISSUE TITLE
How to update extensions

### ISSUE THREAD

**Issue by pschultz** [phpenv/phpenv#29] opened 2013-07-21 15:59 UTC
Is there a way to update extensions and pick a version for installation? I'm trying to build PHP 5.5.1 and the xdebug extension amongst others is out of date:

```
$ ~/.phpenv/php-src/ext/xdebug[(no branch)*]$ git describe --tags
XDEBUG_2_2_1-41-g9b61990
```

PHP 5.5 support was added in 2.2.3, so I want to update the extension. Also, is there a way to pick a specific version for an extension, for example because the latest isn't working with an old PHP?

**Comment by madumlao** [comment] 2018-10-05 07:19
Closing as a duplicate of #57

phpenv has changed dramatically since the last release due to the project having basically died and just recently being revived in #85. Specifically, phpenv now relegates build functionality to [php-build](https://github.com/php-build/php-build), which uses the extension code from the php sources.

The latest phpenv + php-build combo now successfully builds without issues and can be installed using the installer script, phpenv-installer

**Closed by madumlao** 2018-10-05 07:19 UTC
