### ISSUE TITLE
Missing in Documentation

### ISSUE THREAD

**Issue by Abuelodelanada** [phpenv/phpenv#42] opened 2014-01-02 20:50 UTC
Please can you add to the documentatio that you have to install:

$ sudo apt-get install apache2-dev

If you have not, the following error occurs:

$ phpenv global
phpenv v0.0.4-dev

system
/home/jose/.phpenv/libexec/phpenv-global: línea 53: /usr/bin/apxs2: No existe el archivo o el directorio

**Comment by madumlao** [comment] 2018-10-05 06:08
Closing as a duplicate of #57

phpenv has changed dramatically since the last release due to the project having basically died and just recently being revived in #85. Specifically, phpenv no longer bundles in build functionality, which is relegated to [php-build](https://github.com/php-build/php-build). Furthermore, php-build no longer requires the apxs tool or libraries to build successfully.

The latest phpenv + php-build combo now builds successfully. Build issues should now be raised in php-build.

The latest phpenv + php-build combo can be installed using the [phpenv-installer](https://github.com/phpenv/phpenv-installer)

**Closed by madumlao** 2018-10-05 06:08 UTC
