### ISSUE TITLE
PHP 7 support

### ISSUE THREAD

**Issue by sjelfull** [phpenv/phpenv#64] opened 2016-01-06 11:58 UTC
Is there any plans to add PHP 7 support?

**Comment by madumlao** [comment] 2018-10-05 04:56
Closing as a duplicate of #57 

phpenv now supports all versions of php supported by [php-build](https://github.com/php-build/php-build). As of current, php-build supports up to 7.3.

The latest version of phpenv + php-build can automatically be installed using [phpenv-installer](https://github.com/phpenv/phpenv-installer).

**Closed by madumlao** 2018-10-05 04:56 UTC
