### ISSUE TITLE
OSX 10.8.3 'phpenv install --releases' problems

### ISSUE THREAD

**Issue by ivanblagdan** [phpenv/phpenv#19] opened 2013-03-25 11:11 UTC
Just getting phpenv version info on the shell, nothing to install actually. I also tried doing a 'git submodule update --init' to see if anything major was missing.
Anything that I might be missing to get this running?
Thanks.

**Comment by davidqhog** [comment] 2015-01-22 11:53
I found a way round this on the web (can't recollect the guy's name now). Try:
cd ~/.phpenv/php-ext/http
git checkout master
cd ../../
git add php-ext/http
git commit -m "http"

Sets up a  local version in http and I dound everything worked fine after that.

**Comment by colinodell** [comment] 2015-03-23 16:23
+1  I have the same issue as @maxrice and @rodfersou on Linux Mint 17.1.

**Comment by messinadm** [comment] 2015-10-23 04:40
@davidqhog your fix almost worked for me...

fatal: reference is not a tree: 4f5c3c8b8b58ffc1ef0f70e3b347dfbb6b63fd0f
fatal: reference is not a tree: c634cc5fdcd125d8f9779d2b2389534ee6d1a618
Unable to checkout '4f5c3c8b8b58ffc1ef0f70e3b347dfbb6b63fd0f' in submodule path 'php-ext/http'
Unable to checkout 'c634cc5fdcd125d8f9779d2b2389534ee6d1a618' in submodule path 'php-ext/mongo

I had to do the same process for mongo that you did for http as well, then a deep-clean, then --releases worked.

**Comment by kalaomer** [comment] 2016-01-09 14:15
+1 :disappointed:

**Comment by sagikazarmark** [comment] 2016-01-11 17:12
Same here on AntergOS, even with https://github.com/madumlao/phpenv

/cc @madumlao

**Comment by nkiermaier** [comment] 2016-11-04 21:16
My solution for this was to run the command inside the directory that my .phpenv folder is in. 
Also cloning the repo the default branch is DEV! So be sure to switch to master.

Hopes this helps.

**Comment by vigo** [comment] 2017-04-26 11:42
can not install any verisons of php. `phpenv install --releases` returns nothing.

**Comment by madumlao** [comment] 2018-10-05 06:14
Closing as a duplicate of #57

phpenv has changed dramatically since the last release due to the project having basically died and just recently being revived in #85. Specifically, phpenv now relegates build functionality to [php-build](https://github.com/php-build/php-build). Any build issues should now be raised there.

The latest phpenv + php-build combo now successfully builds without issues and can be installed using the installer script, [phpenv-installer](https://github.com/phpenv/phpenv-installer)

**Closed by madumlao** 2018-10-05 06:14 UTC
