### ISSUE TITLE
Lingering issues remain after update

### ISSUE THREAD

**Issue by nickl-** [phpenv/phpenv#22] opened 2013-05-01 16:59 UTC
As @MarcoDeBortoli points out at #21 doing a git pull to get the latest source is not enough to avoid latent troubles which may remain in the submodules or php-src folders.

What he reported was a need to physically remove the php-src and submodules and have them reinstalled. Ideally a solution which would not require completely deleting the repos would be more desirable. Something in combination with --deep-clean that would do a submodule update too perhaps.

For the time being please provide insights if you find any that may help us solve the actual problems while taking note that you should try removing the repos after an update to see if starting from scratch resolves the lingering issues.

**Comment by madumlao** [comment] 2018-10-05 07:20
Closing as a duplicate of #57

phpenv has changed dramatically since the last release due to the project having basically died and just recently being revived in #85. Specifically, phpenv now relegates build functionality to [php-build](https://github.com/php-build/php-build). Any build issues should now be raised there.

The latest phpenv + php-build combo now successfully builds without issues and can be installed using the installer script, [phpenv-installer](https://github.com/phpenv/phpenv-installer)

**Closed by madumlao** 2018-10-05 07:20 UTC
Labels: bug, enhancement
