### ISSUE TITLE
Php-Fpm is installed but not in path

### ISSUE THREAD

**Issue by bes1002t** [phpenv/phpenv#81] opened 2017-09-22 10:16 UTC
Hi,

I've installed php 7.1.8 via php-build plugin for phpenv. It installed also php-fpm, so a php-fpm executable is located in .phpenv/versions/7.1.8/sbin/php-fpm. All other executables like php itself are located in .phpenv/versions/7.1.8/bin/.

When I type "which php" the command line returns ".phpenv/shims/", so I think there is some kind of redirect in that shims directory that redirects to .phpenv/versions/7.1.8/bin/php. But for any reason there is no redirect in that shims directory that redirects to .phpenv/versions/7.1.8/sbin/php-fpm. Someone an idea how I can use the php-fpm like php? I need it to generate the php-fpm.sock for nginx.

**Comment by bes1002t** [comment] 2017-11-28 23:10
Ok I ended up by adding php-fpm manually to my path, so everytime I update php I have to update my path because there is no shim. Besides I found a startscript at the web that works with some small modifications. You can find it here: https://gist.github.com/bes1002t/a3d8940688548dafad25e03fd612eaef

**Comment by madumlao** [comment] 2018-10-05 04:52
Closing as a duplicate of #57 

phpenv should be working using the latest versions pulled by [phpenv-installer](https://github.com/phpenv/phpenv-installer)

Just tested by installing a fresh phpenv and PHP 7.2.1. php-fpm appears in the shims directory.

Running the installer
~~~
madumlao@lenneth ~ $ curl -L https://raw.githubusercontent.com/phpenv/phpenv-installer/master/bin/phpenv-installer \
    | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  3648  100  3648    0     0   3384      0  0:00:01  0:00:01 --:--:--  3387
INFO
 |  $PHPENV_ROOT is defined as /home/madumlao/.phpenv

Installing phpenv
Cloning into '/home/madumlao/.phpenv'...
remote: Counting objects: 1168, done.
remote: Compressing objects: 100% (24/24), done.
remote: Total 1168 (delta 23), reused 32 (delta 19), pack-reused 1125
Receiving objects: 100% (1168/1168), 226.35 KiB | 168.00 KiB/s, done.
Resolving deltas: 100% (720/720), done.
Checking connectivity... done.
 |  Done.

Installing php-build/php-build
 |  Done.

Installing madumlao/phpenv-aliases
 |  Done.

Installing ngyuki/phpenv-composer
 |  Done.

Alright!
 |  Execute:
 |  `phpenv commands`       to see all you can do
 |  `phpenv help <command>` for information on a specific command
~~~

Installing 7.2.1
~~~
madumlao@lenneth ~ $ phpenv install 7.2.1
[Info]: Appending build output to /tmp/php-build.7.2.1.20181005123124.log
[Info]: Loaded extension plugin
[Info]: Loaded apc Plugin.
[Info]: Loaded composer Plugin.
[Info]: Loaded github Plugin.
[Info]: Loaded uprofiler Plugin.
[Info]: Loaded xdebug Plugin.
[Info]: Loaded xhprof Plugin.
[Info]: Loaded zendopcache Plugin.
[Info]: php.ini-production gets used as php.ini
[Info]: Building 7.2.1 into /home/madumlao/.phpenv/versions/7.2.1
[Downloading]: https://secure.php.net/distributions/php-7.2.1.tar.bz2
[Preparing]: /tmp/php-build/source/7.2.1
[Compiling]: /tmp/php-build/source/7.2.1
[xdebug]: Installing version 2.6.1
[Downloading]: http://xdebug.org/files/xdebug-2.6.1.tgz
[xdebug]: Compiling xdebug in /tmp/php-build/source/xdebug-2.6.1
[xdebug]: Installing xdebug configuration in /home/madumlao/.phpenv/versions/7.2.1/etc/conf.d/xdebug.ini
[xdebug]: Cleaning up.
[Info]: Enabling Opcache...
[Info]: Done
[Info]: The Log File is not empty, but the Build did not fail. Maybe just warnings got logged. You can review the log in /tmp/php-build.7.2.1.20181005123124.log
[Success]: Built 7.2.1 successfully.
7.2 => 7.2.1
Warning: This development build of composer is over 60 days old. It is recommended to update it by running "/home/madumlao/bin/composer self-update" to get the latest version.
Warning: This development build of composer is over 60 days old. It is recommended to update it by running "/home/madumlao/bin/composer self-update" to get the latest version.
Warning: This development build of composer is over 60 days old. It is recommended to update it by running "/home/madumlao/bin/composer self-update" to get the latest version.
Warning: This development build of composer is over 60 days old. It is recommended to update it by running "/home/madumlao/bin/composer self-update" to get the latest version.
~~~

Checking contents of shims:
~~~
madumlao@lenneth ~ $ ls .phpenv/shims    
composer  laravel  phar  phar.phar  php  php-cgi  php-config  phpdbg  php-fpm  phpize
~~~

Checking functionality of php-fpm:
~~~
madumlao@lenneth ~ $ phpenv global 7.2.1 
7.2.1
madumlao@lenneth ~ $ phpenv which php-fpm
/home/madumlao/.phpenv/versions/7.2.1/sbin/php-fpm
~~~

**Closed by madumlao** 2018-10-05 04:52 UTC
